### ISSUE TITLE
how to  get

### ISSUE THREAD

**Issue by zhanghongyong123456** [oftheheadland/artbreeder-downloader#1]
Q1: Not very good at Java, how to use;Q2 I am interested in what model of GAN is used to realize Artbreeder scene editing, and I hope you can give me an answer, like the one in the picture below
![01](https://user-images.githubusercontent.com/48466610/116169562-89b03b00-a737-11eb-865a-054ee4dd5e99.png)

**Comment by oftheheadland** [comment]
@zhanghongyong123456 Thanks for asking. You should try asking your question in the official repository here https://github.com/joel-simon/ganbreeder
